/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ListeningHistory = IDL.Record({
  'song' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'song' : IDL.Text,
  'user' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Genre = IDL.Variant({
  'pop' : IDL.Null,
  'rnb' : IDL.Null,
  'reggae' : IDL.Null,
  'metal' : IDL.Null,
  'country' : IDL.Null,
  'folk' : IDL.Null,
  'jazz' : IDL.Null,
  'punk' : IDL.Null,
  'rock' : IDL.Null,
  'soul' : IDL.Null,
  'hipHop' : IDL.Null,
  'latin' : IDL.Null,
  'blues' : IDL.Null,
  'electronic' : IDL.Null,
  'dance' : IDL.Null,
  'classical' : IDL.Null,
});
export const Song = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'genres' : IDL.Vec(Genre),
  'artist' : IDL.Text,
  'coverArt' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'sharedWith' : IDL.Vec(IDL.Principal),
  'songIds' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'favoriteGenres' : IDL.Vec(Genre),
});
export const SharedFile = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([ChatMessage], [], []),
  'addListeningHistory' : IDL.Func([ListeningHistory], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addSong' : IDL.Func([Song], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([Playlist], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getListeningHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ListeningHistory)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
  'getPlaylistsContainingSong' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Playlist)],
      ['query'],
    ),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getSharedFiles' : IDL.Func([], [IDL.Vec(SharedFile)], ['query']),
  'getSong' : IDL.Func([IDL.Text], [IDL.Opt(Song)], ['query']),
  'getSongsByGenre' : IDL.Func([Genre], [IDL.Vec(Song)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareFile' : IDL.Func([SharedFile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ListeningHistory = IDL.Record({
    'song' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'song' : IDL.Text,
    'user' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Genre = IDL.Variant({
    'pop' : IDL.Null,
    'rnb' : IDL.Null,
    'reggae' : IDL.Null,
    'metal' : IDL.Null,
    'country' : IDL.Null,
    'folk' : IDL.Null,
    'jazz' : IDL.Null,
    'punk' : IDL.Null,
    'rock' : IDL.Null,
    'soul' : IDL.Null,
    'hipHop' : IDL.Null,
    'latin' : IDL.Null,
    'blues' : IDL.Null,
    'electronic' : IDL.Null,
    'dance' : IDL.Null,
    'classical' : IDL.Null,
  });
  const Song = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'genres' : IDL.Vec(Genre),
    'artist' : IDL.Text,
    'coverArt' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'sharedWith' : IDL.Vec(IDL.Principal),
    'songIds' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'favoriteGenres' : IDL.Vec(Genre),
  });
  const SharedFile = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([ChatMessage], [], []),
    'addListeningHistory' : IDL.Func([ListeningHistory], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addSong' : IDL.Func([Song], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([Playlist], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getListeningHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ListeningHistory)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
    'getPlaylistsContainingSong' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getSharedFiles' : IDL.Func([], [IDL.Vec(SharedFile)], ['query']),
    'getSong' : IDL.Func([IDL.Text], [IDL.Opt(Song)], ['query']),
    'getSongsByGenre' : IDL.Func([Genre], [IDL.Vec(Song)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareFile' : IDL.Func([SharedFile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };