/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export type Genre = { 'pop' : null } |
  { 'rnb' : null } |
  { 'reggae' : null } |
  { 'metal' : null } |
  { 'country' : null } |
  { 'folk' : null } |
  { 'jazz' : null } |
  { 'punk' : null } |
  { 'rock' : null } |
  { 'soul' : null } |
  { 'hipHop' : null } |
  { 'latin' : null } |
  { 'blues' : null } |
  { 'electronic' : null } |
  { 'dance' : null } |
  { 'classical' : null };
export interface ListeningHistory {
  'song' : string,
  'user' : Principal,
  'timestamp' : bigint,
}
export interface Playlist {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'sharedWith' : Array<Principal>,
  'songIds' : Array<string>,
}
export interface Review {
  'id' : string,
  'song' : string,
  'user' : Principal,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface SharedFile {
  'id' : string,
  'file' : ExternalBlob,
  'sender' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'receiver' : [] | [Principal],
}
export interface Song {
  'id' : string,
  'title' : string,
  'album' : string,
  'lyrics' : string,
  'file' : [] | [ExternalBlob],
  'genres' : Array<Genre>,
  'artist' : string,
  'coverArt' : [] | [ExternalBlob],
}
export interface UserProfile {
  'id' : string,
  'bio' : string,
  'name' : string,
  'favoriteGenres' : Array<Genre>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'addListeningHistory' : ActorMethod<[ListeningHistory], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addSong' : ActorMethod<[Song], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlaylist' : ActorMethod<[Playlist], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getListeningHistory' : ActorMethod<[Principal], Array<ListeningHistory>>,
  'getPlaylist' : ActorMethod<[string], [] | [Playlist]>,
  'getPlaylistsContainingSong' : ActorMethod<[string], Array<Playlist>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getSharedFiles' : ActorMethod<[], Array<SharedFile>>,
  'getSong' : ActorMethod<[string], [] | [Song]>,
  'getSongsByGenre' : ActorMethod<[Genre], Array<Song>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shareFile' : ActorMethod<[SharedFile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];