/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Review {
    id: string;
    song: string;
    user: Principal;
    comment: string;
    timestamp: bigint;
    rating: bigint;
}
export interface ListeningHistory {
    song: string;
    user: Principal;
    timestamp: bigint;
}
export interface Song {
    id: string;
    title: string;
    album: string;
    lyrics: string;
    file?: ExternalBlob;
    genres: Array<Genre>;
    artist: string;
    coverArt?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Playlist {
    id: string;
    title: string;
    owner: Principal;
    sharedWith: Array<Principal>;
    songIds: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ChatMessage {
    id: string;
    content: string;
    sender: Principal;
    timestamp: bigint;
}
export interface UserProfile {
    id: string;
    bio: string;
    name: string;
    favoriteGenres: Array<Genre>;
}
export interface SharedFile {
    id: string;
    file: ExternalBlob;
    sender: Principal;
    message: string;
    timestamp: bigint;
    receiver?: Principal;
}
export enum Genre {
    pop = "pop",
    rnb = "rnb",
    reggae = "reggae",
    metal = "metal",
    country = "country",
    folk = "folk",
    jazz = "jazz",
    punk = "punk",
    rock = "rock",
    soul = "soul",
    hipHop = "hipHop",
    latin = "latin",
    blues = "blues",
    electronic = "electronic",
    dance = "dance",
    classical = "classical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChatMessage(message: ChatMessage): Promise<void>;
    addListeningHistory(history: ListeningHistory): Promise<void>;
    addReview(review: Review): Promise<void>;
    addSong(song: Song): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPlaylist(playlist: Playlist): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(): Promise<Array<ChatMessage>>;
    getListeningHistory(user: Principal): Promise<Array<ListeningHistory>>;
    getPlaylist(id: string): Promise<Playlist | null>;
    getPlaylistsContainingSong(songId: string): Promise<Array<Playlist>>;
    getReviews(): Promise<Array<Review>>;
    getSharedFiles(): Promise<Array<SharedFile>>;
    getSong(id: string): Promise<Song | null>;
    getSongsByGenre(genre: Genre): Promise<Array<Song>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    shareFile(sharedFile: SharedFile): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Genre as _Genre, Playlist as _Playlist, SharedFile as _SharedFile, Song as _Song, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChatMessage(arg0: ChatMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0);
            return result;
        }
    }
    async addListeningHistory(arg0: ListeningHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addListeningHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListeningHistory(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addSong(arg0: Song): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSong(await to_candid_Song_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSong(await to_candid_Song_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlaylist(arg0: Playlist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages();
            return result;
        }
    }
    async getListeningHistory(arg0: Principal): Promise<Array<ListeningHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListeningHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListeningHistory(arg0);
            return result;
        }
    }
    async getPlaylist(arg0: string): Promise<Playlist | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylist(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylist(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaylistsContainingSong(arg0: string): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylistsContainingSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylistsContainingSong(arg0);
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getSharedFiles(): Promise<Array<SharedFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedFiles();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedFiles();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSong(arg0: string): Promise<Song | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByGenre(arg0: Genre): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByGenre(to_candid_Genre_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByGenre(to_candid_Genre_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async shareFile(arg0: SharedFile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareFile(await to_candid_SharedFile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareFile(await to_candid_SharedFile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Genre_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_SharedFile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedFile): Promise<SharedFile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Song_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Promise<Song> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Playlist]): Playlist | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Song]): Promise<Song | null> {
    return value.length === 0 ? null : await from_candid_Song_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    favoriteGenres: Array<_Genre>;
}): {
    id: string;
    bio: string;
    name: string;
    favoriteGenres: Array<Genre>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        favoriteGenres: from_candid_vec_n19(_uploadFile, _downloadFile, value.favoriteGenres)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    sender: Principal;
    message: string;
    timestamp: bigint;
    receiver: [] | [Principal];
}): Promise<{
    id: string;
    file: ExternalBlob;
    sender: Principal;
    message: string;
    timestamp: bigint;
    receiver?: Principal;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.file),
        sender: value.sender,
        message: value.message,
        timestamp: value.timestamp,
        receiver: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.receiver))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    album: string;
    lyrics: string;
    file: [] | [_ExternalBlob];
    genres: Array<_Genre>;
    artist: string;
    coverArt: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    album: string;
    lyrics: string;
    file?: ExternalBlob;
    genres: Array<Genre>;
    artist: string;
    coverArt?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        album: value.album,
        lyrics: value.lyrics,
        file: record_opt_to_undefined(await from_candid_opt_n33(_uploadFile, _downloadFile, value.file)),
        genres: from_candid_vec_n19(_uploadFile, _downloadFile, value.genres),
        artist: value.artist,
        coverArt: record_opt_to_undefined(await from_candid_opt_n33(_uploadFile, _downloadFile, value.coverArt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pop: null;
} | {
    rnb: null;
} | {
    reggae: null;
} | {
    metal: null;
} | {
    country: null;
} | {
    folk: null;
} | {
    jazz: null;
} | {
    punk: null;
} | {
    rock: null;
} | {
    soul: null;
} | {
    hipHop: null;
} | {
    latin: null;
} | {
    blues: null;
} | {
    electronic: null;
} | {
    dance: null;
} | {
    classical: null;
}): Genre {
    return "pop" in value ? Genre.pop : "rnb" in value ? Genre.rnb : "reggae" in value ? Genre.reggae : "metal" in value ? Genre.metal : "country" in value ? Genre.country : "folk" in value ? Genre.folk : "jazz" in value ? Genre.jazz : "punk" in value ? Genre.punk : "rock" in value ? Genre.rock : "soul" in value ? Genre.soul : "hipHop" in value ? Genre.hipHop : "latin" in value ? Genre.latin : "blues" in value ? Genre.blues : "electronic" in value ? Genre.electronic : "dance" in value ? Genre.dance : "classical" in value ? Genre.classical : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Genre>): Array<Genre> {
    return value.map((x)=>from_candid_Genre_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SharedFile>): Promise<Array<SharedFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SharedFile_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Promise<Array<Song>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Song_n31(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Genre_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_SharedFile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SharedFile): Promise<_SharedFile> {
    return await to_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_Song_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Song): Promise<_Song> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    favoriteGenres: Array<Genre>;
}): {
    id: string;
    bio: string;
    name: string;
    favoriteGenres: Array<_Genre>;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        favoriteGenres: to_candid_vec_n11(_uploadFile, _downloadFile, value.favoriteGenres)
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: ExternalBlob;
    sender: Principal;
    message: string;
    timestamp: bigint;
    receiver?: Principal;
}): Promise<{
    id: string;
    file: _ExternalBlob;
    sender: Principal;
    message: string;
    timestamp: bigint;
    receiver: [] | [Principal];
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        sender: value.sender,
        message: value.message,
        timestamp: value.timestamp,
        receiver: value.receiver ? candid_some(value.receiver) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    album: string;
    lyrics: string;
    file?: ExternalBlob;
    genres: Array<Genre>;
    artist: string;
    coverArt?: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    album: string;
    lyrics: string;
    file: [] | [_ExternalBlob];
    genres: Array<_Genre>;
    artist: string;
    coverArt: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        album: value.album,
        lyrics: value.lyrics,
        file: value.file ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file)) : candid_none(),
        genres: to_candid_vec_n11(_uploadFile, _downloadFile, value.genres),
        artist: value.artist,
        coverArt: value.coverArt ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.coverArt)) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    pop: null;
} | {
    rnb: null;
} | {
    reggae: null;
} | {
    metal: null;
} | {
    country: null;
} | {
    folk: null;
} | {
    jazz: null;
} | {
    punk: null;
} | {
    rock: null;
} | {
    soul: null;
} | {
    hipHop: null;
} | {
    latin: null;
} | {
    blues: null;
} | {
    electronic: null;
} | {
    dance: null;
} | {
    classical: null;
} {
    return value == Genre.pop ? {
        pop: null
    } : value == Genre.rnb ? {
        rnb: null
    } : value == Genre.reggae ? {
        reggae: null
    } : value == Genre.metal ? {
        metal: null
    } : value == Genre.country ? {
        country: null
    } : value == Genre.folk ? {
        folk: null
    } : value == Genre.jazz ? {
        jazz: null
    } : value == Genre.punk ? {
        punk: null
    } : value == Genre.rock ? {
        rock: null
    } : value == Genre.soul ? {
        soul: null
    } : value == Genre.hipHop ? {
        hipHop: null
    } : value == Genre.latin ? {
        latin: null
    } : value == Genre.blues ? {
        blues: null
    } : value == Genre.electronic ? {
        electronic: null
    } : value == Genre.dance ? {
        dance: null
    } : value == Genre.classical ? {
        classical: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Genre>): Array<_Genre> {
    return value.map((x)=>to_candid_Genre_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
